### ISSUE TITLE
Auto Vo has stopped working, and reinstalling not working

### ISSUE THREAD

**Issue by lloydi** [ckundo/auto-vo#20]
So, I had this working perfectly well on two different computers. Today I am getting this error:

npm ERR! syscall chmod
npm ERR! path /Users/username/.npm/_npx/12493/lib/node_modules/auto-vo/bin/voiceover.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/username/.npm/_npx/12493/lib/node_modules/auto-vo/bin/voiceover.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I then tried reinstalling in terminal with:

npm install -g auto-vo

And this errors too:

/usr/local/bin/auto-vo -> /usr/local/lib/node_modules/auto-vo/bin/auto-vo.js
npm WARN rollback Rolling back playwright-webkit@1.18.1 failed (this is probably harmless): EINVAL: invalid argument, rmdir '/usr/local/lib/node_modules/auto-vo/node_modules/playwright-webkit/node_modules/playwright-core/lib/third_party/highlightjs/highlightjs'
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/auto-vo/bin/voiceover.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/auto-vo/bin/voiceover.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2022-01-30T21_27_20_909Z-debug.log

Any idea what is happening and how I resolve it?

**Comment by ckundo** [comment]
thanks @lloydi , this is resolved in `v1.6.0`!

**Comment by lloydi** [comment]
I am not sure what I am doing wrong, but I pulled latest from GH, and have also run the npm install, but am still getting the same issues as above. Is there a step/config or similar that I need to run?

Thanks :)

**Comment by ckundo** [comment]
@lloydi ah, this is caused by #17, the bin script was still referenced... I removed it in v1.7.0. thanks for your patience!

**Comment by ckundo** [comment]
I'm going to reopen while I double check this issue.

**Comment by ckundo** [comment]
@lloydi there was also an incorrect path in the auto-vo bin script. fixed that also, v1.7.2

**Comment by lloydi** [comment]
I'm trying this again now. I just successfully ran 

npm install -g auto-vo

Did not error this time on install. Will now check next step. Thanks for looking at this :)

**Comment by ckundo** [comment]
@lloydi I'll close this, feel free to reopen if it's still an issue.

**Comment by lloydi** [comment]
Thank you. I got it running yesterday after you made those tweaks :)
